import './globals.css'
// 1. Noto_Sans_JP をインポートします
import { Noto_Sans_JP } from 'next/font/google'

// 2. Noto Sans JP の設定を記述します
const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '700'], // 通常の太さと太字
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.Node
}) {
  return (
    // 3. 言語を 'ja' にし、className を変更します
    <html lang="ja">
      <body className={notoSansJP.className}>{children}</body>
    </html>
  )
}