import './globals.css'
import { Noto_Sans_JP } from 'next/font/google'
// ステップ1で作成したファイルをインポートします
import StyledComponentsRegistry from './lib/registry'

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        {/* children全体をStyledComponentsRegistryで囲みます */}
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}